version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pp-postgres
    restart: unless-stopped
    ports:
      - "8181:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-pingpanther}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-0233dc26fbc48120667a68d836c39303693afecb94f4f3f91583d4120e47d758}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pp-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pp-redis
    restart: unless-stopped
    ports:
      - "8182:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-7032b9969aa37e27be1f6324f71eb3bec168f51cf11edfc8560daba34fe900b7}
    volumes:
      - redis_data:/data
    networks:
      - pp-network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  pp-network:
    driver: bridge
